### ISSUE TITLE
when I use Keyboard.h, could I press keycode instead of keyASCII？

### ISSUE THREAD

**Issue by ljq29** [arduino-libraries/Keyboard#26] opened 2019-12-03 14:17 UTC
It is generally accepted that when the header file Keyboard.h is used, some control keys can be sent through the Keyboard.press (key) function. But for keys without ASCII values, such as KEYCODE_VOLUME_UP and KEYCODE_VOLUME_DOWN, how should they be sent to the host through arduino?

**Comment by anaicagrouver** [comment] 2020-03-04 15:44
0x80	Keyboard Volume Up
0x81	Keyboard Volume Down
0x7F	Keyboard Mute
You can also see the list [here](https://www.arduino.cc/en/Reference/KeyboardModifiers)

**Comment by thekunalsaini** [comment] 2020-03-18 12:42
@ljq29  you can use hex codes for this

**Comment by ljq29** [comment] 2020-03-18 13:48
> @ljq29 you can use hex codes for this

So, from where I can find the table of keycode 2 hex?

**Comment by thekunalsaini** [comment] 2020-03-18 15:42
@ljq29  Google it man it is easily available

**Comment by thekunalsaini** [comment] 2020-03-18 15:42
If @ljq29 you are satisfied give a good feedback ;)

**Comment by edgar-bonet** [comment] 2024-12-07 17:56
Closing this as a duplicate of issue #17.

**Closed by edgar-bonet** 2024-12-07 17:56 UTC
Labels: type: enhancement, topic: code
