### ISSUE TITLE
Nano33 IoT

### ISSUE THREAD

**Issue by tikonen** [arduino-libraries/Keyboard#41] opened 2020-11-19 14:34 UTC
Hi,

Should this library (and Mouse) work on Nano33 IoT? It compiles and links fine but the USB device does not work at least on Windows. What I get is weird broken composite device with two CDC (COM port) devices.

I bought this board based on few articles in the Webs that state native-USB HID support.  Maybe this was false information?
Looking closer I believe Arduino never claimed anywhere to support USB HID core on this specific board but it states here https://www.arduino.cc/reference/en/language/functions/usb/keyboard/ that "The keyboard functions enable 32u4 or **SAMD** micro based boards to send keystrokes to an attached computer through their micro’s native USB port."

Thank you!

**Comment by facchinm** [comment] 2020-11-19 14:42
Hi @tikonen ,
on Windows the driver situation for composite devices is a mess. If your board has already been recognized as single CDC at least once the only thing you can do is uninstalling its driver and let Windows repeat the installation on its own (see https://github.com/arduino/ArduinoCore-samd/issues/423#issuecomment-615093627).
Let me know if it works

**Comment by tikonen** [comment] 2020-11-19 14:46
Thank you for prompt reply, I'll look into the linked issue.

**Comment by PaulStoffregen** [comment] 2020-11-19 23:23
@facchinm - You should be able to solve this by just increasing the BCD version number in the device descriptor.  Windows will automatically re-detect the device when it sees the same device with a new BCD version number.

**Comment by tikonen** [comment] 2020-11-20 07:05
Looks like there is no way to uninstall driver. The device is recognized as common composite device and uses built-in drivers. I've attached picture of device manager and USB device dump
 of the device.

![Device Manager](https://user-images.githubusercontent.com/380448/99769748-7c9b7a00-2b0f-11eb-9998-9890ca0f99ff.PNG)

[USB device dump.txt](https://github.com/arduino-libraries/Keyboard/files/5571776/composite.txt)

**Comment by facchinm** [comment] 2020-11-20 08:20
> @facchinm - You should be able to solve this by just increasing the BCD version number in the device descriptor. Windows will automatically re-detect the device when it sees the same device with a new BCD version number.

That's definitely something I have to investigate, thanks for the hint!

@tikonen you shouldn't uninstall the composite device, only the serial "association" with Arduino CDC driver (the device showings as Nano33 IoT)

**Comment by tikonen** [comment] 2020-11-20 08:49
> @tikonen you shouldn't uninstall the composite device, only the serial "association" with Arduino CDC driver (the device showings as Nano33 IoT)

I tried that just now, the only difference is that the COM port order reversed in USB descriptor.

**Comment by facchinm** [comment] 2020-11-20 10:32
So HID part of the composite device is not recognized at all? Can you send a screenshot of the whole device manager?

**Comment by tikonen** [comment] 2020-11-20 10:54
Now it works! I had forgot to tick the checkbox "Delete the driver software for this device" when uinstalling the driver. Windows always silently reused the samd driver.

**Comment by per1234** [comment] 2022-03-06 21:35
Closing as duplicate of https://github.com/arduino/ArduinoCore-samd/issues/423#issuecomment-615093627

**Closed by per1234** 2022-03-06 21:35 UTC
